---
creation_rules:
  - path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    age: "age13503lmc3l9u90mmvry9efefeynat82sffh8gf0augsk0r6twdyhsdc5fwe"
  - path_regex: (bootstrap|kubernetes)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    age: "age13503lmc3l9u90mmvry9efefeynat82sffh8gf0augsk0r6twdyhsdc5fwe"
stores:
  yaml:
    indent: 2
