# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:c3IwOOs2RNCLmGdxfJ4CEm8Msw37sjmDWMgWiVcW2Uo=,iv:p98nh28YLTMGwDikm+5TJelXzeA4c+lmhu0iKv9RHus=,tag:IPDgdc13t427Esn26E/5iw==,type:str]
sops:
  age:
    - recipient: age13503lmc3l9u90mmvry9efefeynat82sffh8gf0augsk0r6twdyhsdc5fwe
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXTFJWb1Q0RExmYmx4bDlC
        RDRaQ2o4WkpDenRYY24rc2lqWXRDejZLNkNZCnNIN1p5dWdSMGJBOHVwclVGaUhW
        Y1FyNi9RWk9sMXh1MmFxODdhZVcxdGsKLS0tIEJCSSthV2RubjdlMFRGczNGUnpX
        bDFkbFMrR3BNZjErS1E2MkV5YTNONmcKmmkw+JmbYtM0/dbhcKGHxB5thc79G2qX
        8KNcjKfM1sxu2Bb3Pc3iN4VMTNdnCSdO8e7yRsdEqelk6HMugT02Jw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-19T01:52:53Z"
  mac: ENC[AES256_GCM,data:DzAIjC0szwpzn5xrk9XwzlWjn6YujYVEEkgbRrj63WqFseuz0XzKwmJsXuWx5vX3HSyDo6ThrxQyG6p1k65PtLq7Ze75Z6hlv7plQmUkoRaJ7HnSU3susWSEqU0D3CwSAzLb+hP4aiZu3d1iZtP7kz16fCXQ1JrRonetgv5OwmE=,iv:mScbXIEOPCO1ECUjKkgkyd3dvfGmWEagUlWS2oLJwco=,tag:HO6vR3UiW6fhdw+NKEvUFQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
