apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:Rna6Si/ic0cHvSu3eYI=,iv:5BEQdHxY67DSQ17+9UDHVOx37KKHV2Ag0lta1ehanYE=,tag:9P55U1AGY9I5ouoYaNM37g==,type:str]
sops:
  age:
    - recipient: age13503lmc3l9u90mmvry9efefeynat82sffh8gf0augsk0r6twdyhsdc5fwe
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQbkwxc2c1elY0WGh5UGRl
        Y0RML2lNRWFKajV5YUlqUXpwd0NyZ2ZyaWlrCnBNL1Q3N0dwTnYzQStQNVVIeEdQ
        aC9tNlkweFJWSUQ2eTZGUTMzd0FHL0EKLS0tIHNvRUNxVXBMaUZDTzI0TFRTb3FR
        VEM5Ny9tRklqMDB1ZmRhTFovczYrUUkKMC0BfpEDLvmlFqBVg46QcoUrpPKzfk4x
        74fhPAZ0WJD8PcbnrgavUlUiPuS4mOtu6yYp0OF4ETXilaWSkX/ITA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-18T18:07:01Z"
  mac: ENC[AES256_GCM,data:7kdb7bNqzw02CDAU9WxOBTE1sL1e/bbF60T+rK1Xb3sa3U5hUuqwrBI12MdPsGfYknH3Qa+6Ki0QeJtgxHIfY+FwlcnuaXg1FFsmehBhFbDjAOO4lqACAvSRPno4sbwtqpavMhMilSjNoUSSQ87y0/erbfy9Co2bxtqNXGI6fcc=,iv:sdALlqUQz/kM9+EA+2t8rVeLxajfdrMjSfhMFDuIzLo=,tag:+bzfrzvS9nPo4H9TzL6Dhg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
